"""Turn the generated CSVs into reports/results/results.md.

    python scripts/make_report_tables.py [config.yaml]

Every number in results.md comes from files written by run_experiments.py.
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

import pandas as pd  # noqa: E402

from stylometry.config import PROJECT_ROOT, load_config, rel, resolve  # noqa: E402

EXP_NAMES = {
    "B0": "majority class", "B1": "length only", "E1": "handcrafted (5 groups)", "E2": "char n-grams",
    "E3": "combined", "E4": "best set: split comparison", "E5": "group ablation", "E6": "cross-topic",
}


def pm(row, m, digits=3):
    mean, std = row.get(f"{m}_mean"), row.get(f"{m}_std")
    if pd.isna(mean):
        return "n/a"
    return f"{mean:.{digits}f} ± {std:.{digits}f}"


def main_table(res: pd.DataFrame) -> str:
    rows = []
    for _, r in res.iterrows():
        rows.append({
            "ID": r.exp_id, "experiment": EXP_NAMES.get(r.exp_id, ""), "features": r.feature_set,
            "model": r.model, "split": r.split, "variant": r.variant if isinstance(r.variant, str) else "",
            "macro-F1": pm(r, "f1_macro"),
            "95% CI (macro-F1)": f"[{r.f1_ci_low_mean:.3f}, {r.f1_ci_high_mean:.3f}]",
            "accuracy": pm(r, "accuracy"), "ROC-AUC": pm(r, "roc_auc"),
            "F1 native": pm(r, "f1_native"), "F1 non-native": pm(r, "f1_non_native"),
            "precision (macro)": pm(r, "precision_macro"), "recall (macro)": pm(r, "recall_macro"),
            "seeds": int(r.n_seeds),
        })
    return pd.DataFrame(rows).to_markdown(index=False)


def main(config_path: str | None = None, update_readme: bool | None = None) -> int:
    cfg = load_config(config_path)
    res_dir = resolve(cfg, "results_dir")
    path = res_dir / "results.csv"
    if not path.exists():
        print(f"{rel(path)} not found. Run scripts/run_experiments.py first.")
        return 0
    res = pd.read_csv(path)
    if update_readme is None:          # only the real project config touches the README
        update_readme = config_path is None
    ev = cfg["evaluation"]
    best = json.loads((res_dir / "best.json").read_text()) if (res_dir / "best.json").exists() else {}

    lines = ["# Results", "",
             "Generated by `scripts/make_report_tables.py` from `results.csv`. Do not edit by hand.", "",
             f"Mean ± std over {len(cfg['seeds'])} writer splits (seeds {cfg['seeds']}). "
             "The 95% CI is a bootstrap interval for macro-F1 on each test set, averaged over seeds.", ""]
    if best:
        lines += [f"Best configuration (selected by cross-validation on training writers only): "
                  f"**{best['best_feature_set']} / {best['best_model']}**", ""]

    main_ids = ["B0", "B1", "E1", "E2", "E3"]
    lines += ["## Main comparison (writer-separated test sets)", "",
              main_table(res[res.exp_id.isin(main_ids)]), ""]

    # length-baseline check
    b1 = res[res.exp_id == "B1"]
    full = res[res.exp_id.isin(["E1", "E2", "E3"])]
    if len(b1) and len(full):
        b1_f1 = float(b1.f1_macro_mean.iloc[0])
        top = full.loc[full.f1_macro_mean.idxmax()]
        gap = float(top.f1_macro_mean) - b1_f1
        flag = gap < ev["length_baseline_flag_gap"]
        lines += ["## Length-only baseline check", "",
                  f"Best full model ({top.feature_set} / {top.model}) macro-F1 minus length-only macro-F1: "
                  f"**{gap:+.3f}**.", ""]
        if flag:
            lines += [f"> **Warning:** the gap is below {ev['length_baseline_flag_gap']}. Text length alone "
                      "explains most of the performance; treat the stylometric results with caution.", ""]
        else:
            lines += [f"The gap is at least {ev['length_baseline_flag_gap']}, so the models use more than length.", ""]

    e4 = res[res.exp_id == "E4"]
    if len(e4):
        lines += ["## E4: writer leakage (document-level random split vs writer-separated)", "",
                  main_table(e4), ""]
        for m in e4.model.unique():
            d = e4[(e4.model == m)].set_index("variant")
            if {"document-random", "writer-separated"} <= set(d.index):
                gap = d.loc["document-random", "f1_macro_mean"] - d.loc["writer-separated", "f1_macro_mean"]
                lines.append(f"- {m}: document-random minus writer-separated macro-F1 = **{gap:+.3f}**")
        lines.append("")

    abl_path = res_dir / "ablation.csv"
    if abl_path.exists():
        abl = pd.read_csv(abl_path)
        abl["drop in macro-F1"] = [f"{a:+.3f} ± {b:.3f}" for a, b in zip(abl.f1_drop_mean, abl.f1_drop_std)]
        lines += ["## E5: feature-group ablation (LR on handcrafted features)", "",
                  "Positive = performance falls when the group is removed.", "",
                  abl[["group", "drop in macro-F1"]].to_markdown(index=False), "",
                  main_table(res[res.exp_id == "E5"]), ""]

    gi_path = res_dir / "group_importance.csv"
    if gi_path.exists():
        gi = pd.read_csv(gi_path)
        gi["abs_coef_sum"] = gi.abs_coef_sum.round(3)
        lines += ["## Sum of |coefficient| per group (LR, standardised handcrafted features, seed 0)", "",
                  gi.to_markdown(index=False), ""]

    e6 = res[res.exp_id == "E6"]
    if len(e6):
        lines += ["## E6: cross-topic (train on one prompt, test on the other, unseen writers)", "",
                  main_table(e6), ""]

    l1_path = res_dir / "l1_recall.csv"
    if l1_path.exists():
        l1 = pd.read_csv(l1_path)
        l1["recall"] = l1.recall.round(3)
        lines += ["## Recall per L1 / country (best model, pooled over seeds)", "",
                  "Fairness check: writers with different first languages may be affected differently.", "",
                  l1.to_markdown(index=False), ""]

    prof_path = res_dir / "proficiency_recall.csv"
    if prof_path.exists():
        pr = pd.read_csv(prof_path)
        pr["recall"] = pr.recall.round(3)
        lines += ["## Recall per proficiency level (best model, pooled over seeds)", "",
                  "Share of each group's test texts classified correctly. Low recall for a level means "
                  "those writers are more often labelled with the other class.", "",
                  pr.to_markdown(index=False), ""]

    out = res_dir / "results.md"
    out.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    print(f"wrote {rel(out)}")

    if update_readme:
        readme_block = [f"Mean ± std over {len(cfg['seeds'])} writer-separated splits."]
        if best:
            readme_block.append(f"Best by cross-validation: **{best['best_feature_set']} / {best['best_model']}**.")
        readme_block += ["", main_table(res[res.exp_id.isin(main_ids)])]
        inject_readme("\n".join(readme_block))
    return 0


def inject_readme(block: str, readme: Path = PROJECT_ROOT / "README.md") -> None:
    """Replace the text between the RESULTS markers in README.md."""
    text = readme.read_text(encoding="utf-8")
    pattern = re.compile(r"(<!-- RESULTS:START -->\n).*?(\n<!-- RESULTS:END -->)", re.S)
    if not pattern.search(text):
        print("README.md has no RESULTS markers; skipped")
        return
    readme.write_text(pattern.sub(lambda m: m.group(1) + block + m.group(2), text), encoding="utf-8",
                      newline="\n")
    print("updated results table in README.md")


if __name__ == "__main__":
    sys.exit(main(sys.argv[1] if len(sys.argv) > 1 else None))
