"""Load, clean, filter, balance and save the dataset.

    python scripts/prepare_data.py [config.yaml]

Writes data/processed/dataset.parquet and data/processed/data_summary.md.
If data/raw/ is empty, prints how to get the corpus and exits without error.
"""
from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

import pandas as pd  # noqa: E402

from stylometry.config import PROJECT_ROOT, load_config, rel, resolve, set_seed  # noqa: E402
from stylometry.data.balance import balance_writers  # noqa: E402
from stylometry.data.clean import clean_text, truncate_words, word_count  # noqa: E402
from stylometry.data.loaders import DATA_INSTRUCTIONS, DataNotFoundError, load_raw, raw_data_available  # noqa: E402


def summarize(df: pd.DataFrame, dropped: dict, cfg: dict) -> str:
    d = cfg["data"]
    g = df.groupby("label")
    tbl = pd.DataFrame({
        "texts": g.size(),
        "writers": g.writer_id.nunique(),
        "mean_words_original": g.word_count_original.mean().round(1),
        "mean_words_used": g.word_count.mean().round(1),
        "topics": g.topic.apply(lambda s: ", ".join(sorted(map(str, s.dropna().unique())))),
    })
    lines = [
        "# Data summary",
        "",
        "Generated by `scripts/prepare_data.py`. Do not edit by hand.",
        "",
        f"- source: `{d['source']}`",
        f"- minimum length: {d['min_words']} words",
        f"- truncation: first {d['truncate_words']} words" if d.get("truncate_words") else "- truncation: none",
        f"- balancing: {d['balance']}",
        "",
        "## Texts dropped for being shorter than the minimum",
        "",
        "| label | dropped |",
        "|---|---|",
        *[f"| {k} | {v} |" for k, v in dropped.items()],
        "",
        "## Final dataset",
        "",
        tbl.to_markdown(),
        "",
    ]
    if df["l1"].notna().any():
        l1 = df.groupby(["label", "l1"]).writer_id.nunique().rename("writers").reset_index()
        lines += ["## Writers per L1 / country code", "", l1.to_markdown(index=False), ""]
    if df["proficiency"].notna().any():
        pr = df.groupby(["label", "proficiency"]).writer_id.nunique().rename("writers").reset_index()
        lines += ["## Writers per proficiency level", "", pr.to_markdown(index=False), ""]
    return "\n".join(lines)


def main(config_path: str | None = None) -> int:
    cfg = load_config(config_path)
    set_seed(cfg["seed"])
    d = cfg["data"]

    if not raw_data_available(cfg, PROJECT_ROOT):
        print(DATA_INSTRUCTIONS)
        return 0
    try:
        df = load_raw(cfg, PROJECT_ROOT)
    except DataNotFoundError as e:
        print(f"{e}\n{DATA_INSTRUCTIONS}")
        return 0
    for c in ("topic", "l1", "proficiency"):
        if c not in df.columns:
            df[c] = None
    print(f"loaded {len(df)} texts from {df.writer_id.nunique()} writers")

    df["text"] = [clean_text(t, d.get("header_line_regex")) for t in df["text"]]
    df["word_count_original"] = df["text"].map(word_count)

    short = df.word_count_original < d["min_words"]
    dropped = df[short].label.value_counts().reindex(["native", "non_native"], fill_value=0).to_dict()
    for lab, n in dropped.items():
        print(f"dropped {n} {lab} texts under {d['min_words']} words")
    df = df[~short].reset_index(drop=True)

    if d["balance"] == "downsample":
        before = df.groupby("label").writer_id.nunique().to_dict()
        df = balance_writers(df, cfg["seed"], d.get("balance_strata"))
        after = df.groupby("label").writer_id.nunique().to_dict()
        print(f"writer-level balancing: {before} -> {after}")

    if d.get("truncate_words"):
        df["text"] = [truncate_words(t, d["truncate_words"]) for t in df["text"]]
    df["word_count"] = df["text"].map(word_count)

    out = resolve(cfg, "processed")
    out.parent.mkdir(parents=True, exist_ok=True)
    cols = ["doc_id", "text", "label", "writer_id", "topic", "l1", "proficiency", "source",
            "word_count_original", "word_count"]
    df[cols].to_parquet(out, index=False)
    summary = summarize(df, dropped, cfg)
    resolve(cfg, "data_summary").write_text(summary, encoding="utf-8")
    print(f"saved {len(df)} texts to {rel(out)}")
    print(summary)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1] if len(sys.argv) > 1 else None))
